---
- hosts: all
  tasks:
    - name: start imf-web
      docker_container:
        name: imf-web
        container_default_behavior: compatibility
        image: jaeseoparkdocker/imessageee:latest
        state: started
        ports:
          - 3238:80
