---
- hosts: fatfinger
  tasks:
    - name: Ensure nginx is on the latest version
      apt:
        name: nginx
        state: latest
    - name: Ensure certbot is installed
      apt:
        name: certbot
    - name: Ensure certbot python sdk is installed
      apt:
        name: python3-certbot-nginx
    - name: Ensure nginx config file is present
      copy:
        src: nginx.conf
        dest: /etc/nginx/conf.d/fatfinger.click.conf
    - name: Ensure default config file is absent
      file: name=/etc/nginx/sites-enabled/default state=absent
    - name: Run certbot
      shell: certbot install --nginx -d fatfinger.click,imessageee.fatfinger.click,mlib.fatfinger.click --expand --agree-tos --cert-name fatfinger.click --redirect
      become: yes
      notify: restart nginx
    - name: Ensure the cron job exists
      ansible.builtin.cron:
        name: renew cert
        minute: "0"
        hour: "0"
        job: /usr/bin/certbot renew --quiet
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
