name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Copy files to the html dir via scp
        uses: appleboy/scp-action@master
        with:
          source: build/*
          target: /var/www/html
          strip_components: 1  # This removes the unwanted build/ directory
          overwrite: true
          host: 158.69.60.186
          username: github
          key: ${{ secrets.DEPLOY_PRV_KEY }}
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
