name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Copy files to tmp dir via scp
        uses: appleboy/scp-action@master
        env:
          HOST: 158.69.60.186
          USERNAME: debian
          PORT: 22
          KEY: ${{ secrets.DEPLOY_SSHKEY }}
        with:
          source: build
          target: /tmp/fatfinger
      - name: Move files to the location nginx is watching
        uses: appleboy/ssh-action@master
        with:
          HOST: 158.69.60.186
          USERNAME: debian
          PORT: 22
          KEY: ${{ secrets.SSHKEY }}
          script: sudo mv /tmp/fatfinger/build/* /var/www/html
