name: Deploy

on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: 158.69.60.186
          USERNAME: debian
          PORT: 22
          KEY: ${{ secrets.DEPLOY_SSHKEY }}
        with:
          source: .
          target: /var/www/html
