name: Lint

on: [pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Yarn build # "lint" is not a valid yarn command. A build includes linting.
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
